AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This CloudFormation template creates a CodeBuild Build project that points to
  a public GitHub repository as its source. 
Resources:
  PythonBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      ServiceRole: !Ref CodeBuildRole
      Artifacts:
        Type: NO_ARTIFACTS 
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/python:3.7.1-1.7.0
        EnvironmentVariables:
          - Name: VAR1
            Value: Value1
          - Name: VAR2
            Value: Value2
            Type: PLAINTEXT
      Source:
        Type: GITHUB
        Auth:
            Type: OAUTH 
        BuildSpec: python-example/buildspec.yml
        Location: https://github.com/wes-novack/codebuild-demo
      TimeoutInMinutes: 5 
  CodeBuildRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action: ['sts:AssumeRole']
          Effect: Allow
          Principal:
            Service: [codebuild.amazonaws.com]
        Version: '2012-10-17'
      Path: /
      Policies:
        - PolicyName: CodeBuildAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Action:
                - 'logs:*'
                - 'ec2:CreateNetworkInterface'
                - 'ec2:DescribeNetworkInterfaces'
                - 'ec2:DeleteNetworkInterface'
                - 'ec2:DescribeSubnets'
                - 'ec2:DescribeSecurityGroups'
                - 'ec2:DescribeDhcpOptions'
                - 'ec2:DescribeVpcs'
                - 'ec2:CreateNetworkInterfacePermission'
                Effect: Allow
                Resource: '*'
